spring:
  datasource:
    url: ENC(A+xhyKlTdTHmA9lXjNifMAR9tTqCEEdeDERaWiGEiea6WcOq54g2NPXc70Ts7AZUlsupZ6kOnhvVFpU23E89I3YSc+7jijglwfZG9QpyoSWmFETIYVnLsDoGLFWMGSfZ)
    username: ENC(eYbB907/PxPGSCyeEZ+DMQ==)
    password: ENC(AYyY9n4cMylETc9nS9alNh3/jHuIqMqI)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true # 콘솔창에 쿼리문 출력
    hibernate:
      ddl-auto: validate # DDL 은 SQL에 의해 직접 handling
    properties:
      hibernate:
        format_sql: true # sql문 포맷
#        default_batch_fetch_size: 500 # 일대다 컬렉션 조회 시 성능 최적화
    open-in-view: false # 영속성 컨텍스트의 생존 범위를 트랜잭션 범위로 한정(OSIV)
    database: mysql

  mail:
    host: smtp.gmail.com # Gmail SMTP 서버 호스트
    port: 587 # SMTP 서버의 포트 번호
    username: ENC(rhVwA/gNogsz1Z56JSuskXD2duP8o+MusdLVbKtDmYA=)
    password: ENC(Pf4ikNvFQmfZxjl2qWipR2mR0ZJakc8+ZSSJrFk0QtA=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000 # 유효시간, 30 * 60 * 1000 == 30분

payment:
  toss:
    test_client_api_key: ENC(El1Td3en2NfIIj52q6pit1Av/V51xIosYbNgIOVjTaB4t/9eTI4fXi/bjqai3jkY)
    test_secret_api_key: ENC(Tdk8usZl4X0nGhXsWhcrJ4vjXDLi0SEwxMVOGZv2JOFyD/qS+XhJ1/zd2bn/V3EQ)
    success_url: "http://localhost:8080/api/v1/payments/toss/success"
    fail_url: "http://localhost:8080/api/v1/payments/toss/fail"

server:
  port:443


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace